### PR TITLE
Update null checks and resolve CSProject compliance

### LINKED ISSUE #56: Reference to Spatial_Engine should be set to copy local false
The reference to `Spatial_Engine` within the `TriangleNet_Engine` is set to copy local, when it shouldn't be.

### LINKED ISSUE #71: Resolve null check in methods
The method `BH.Engine.Geometry.Triangulation.Compute.DelaunayTriangulation(Polyline outerCurve, List<Polyline> innerCurves, Double offsetDistance, Boolean conformingDelaunay)` is not handling null inputs and is failing the check for `null-handling`. Because this toolkit feeds into `Test_Toolkit`, this is creating noise for other PRs to check against. Handle the nulls better on this method.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #71 
Fixes #56 

### Additional comments
Fixed the CSProject compliance raised 4 months ago while I was here.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by michaelhoehn — APPROVED** [review]
This LGTM!

**Pull request merged**
