### PR TITLE
Upgrade to .NetStandard2.0

### LINKED ISSUE #110: Upgrade to .NetStandard2.0
#### Description:

Update oM and Engine type of toolkit to .NetStandard2.0 to align with core

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #110

Upgrade to .netstandard 2.0 in alignment with other core

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check project-compliance
@BHoMBot check core
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check project-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
image

I think the issue we have @IsakNaslundBh is that the TriangleNet DLL which the toolkit depends on, can't be loaded into a .NetStandard2.0 system. We need to upgrade the TriangleNet DLL with it I think.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Upgrade has worked successfully following offline discussion with @IsakNaslundBh over the nuget identified as actually not being copied in the post build.

Happy to merge and deploy.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
