### PR TITLE
Added ability for IRationalise to return Polygon and other IPolylines as Polyline for downstream operations

### LINKED ISSUE #136: IRationalise bug for Polygon's fails due to not recognizing as Polyline
#### Description:
Polygon's currently fail for IRationalise, since they are not recognized as a Polyline.

#### Steps to reproduce:
Feed a Polygon into IRationalise. Alternately, try to compute the RenderMesh of a closed polyline, which is how this bug was discovered.

#### Expected behaviour:
Return of the Polygon as a polyline / return of the render mesh for the corresponding closed polyline when computing RenderMesh.

#### Test file(s):
[Test Script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/TriangleNet_Toolkit/%23378-IRationalisePolygon?csf=1&web=1&e=TyyVXy)

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #136 

Fixes bug where IPolylines that were not Polylines were skipped and returned an error.

### Test files
[Test Script](https://github.com/BuroHappoldEngineering/ModelLaundry_Toolkit/issues/378)

### CODE REVIEW

**Review by alelom — APPROVED** [review]
Approving following simple code changes.

**Comment by enarhi** [comment]
@BHoMBot check required

**Comment by enarhi** [comment]
@BHoMBot check compliance
@BHoMBot check ready-to-merge

**Comment by enarhi** [comment]
@BHoMBot check ready-to-merge

**Comment by enarhi** [comment]
@BHoMBot check unit-tests

**Pull request merged**
