### PR TITLE
Fix incorrect check for Intersecting curves when computing Voronoi regions

### LINKED ISSUE #95: Incorrect handling of intersecting end point curves when computing tributary areas
#### Description:

End-point intersecting curves are check incorrectly in the tributary area calculation. Start and end points of the first curve is checked twice, instead of first first curve and then second curve.

#### Steps to reproduce:

Try computing tributary areas with two intersecting curves.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #95

Check if intersection point is end point was checked against the first curve twice instead of first first curve and then second curve.

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EiEigBBMZAJLkDZiU-TpjAEBTh0GOEb43ZdmC_SENq25pA?e=yQ9di1

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Review by JosefTaylor — APPROVED** [review]
Looking at the test script, the original branch did some funny stuff:
image
and this is resolved with the fix.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
