### PR TITLE
Update UnitTest for voronoi region to reflect changes in boundary

### LINKED ISSUE #90: Unittest for VoronoiRegions to be updated
#### Definition of the test :

https://github.com/BHoM/TriangleNet_Toolkit/pull/88/commits/8adf70cdd3204678604494f450e221d10a3e038d had a slight fix to how the automatic boundary is computed. This makes some of the unit tests come back with errors. The relevant info (voronoi cells around the points) is still correct and produces valid results.

Unit tests to be updated to capture the change in boundary behaviour.

### LINKED ISSUE #92: Add UnitTest for curve based voronoi calculations
#### Definition of the test :

Add UnitTests for methods added in https://github.com/BHoM/TriangleNet_Toolkit/pull/88

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #90
Closes #92 

- Updating UT for point based voronoi generation to reflect changes around the boundary
- Adding UTs for mixed curve and point based Voronois

### Test files

File adding the additional tests:

https://burohappold.sharepoint.com/:f:/s/BHoM/EnVmAng5RCNMlQQUYESoRoQBjD7RzsnhFBwC9ZER4z-BUw?e=uz0cLN

File testing that all UTs are passing:

https://burohappold.sharepoint.com/:f:/s/BHoM/Ep3MjOi-vT9Ng19raiAevl8BPREC4nnatHUVLcc5lQo4UQ?e=polRC9

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Updated unit test works well and captures additional elements.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
