### PR TITLE
Adding methods for computing Vronoi diagrams for co-planar curves and Points

### LINKED ISSUE #87: Add method for chelp producing Voronoi regions based on Curves and Points
#### Description:

Curves to be discretised into a set of points and joined using boolean region operations.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #87 

- Adds support for computing Voronoi regions from Points as well as (co) planar curves
- Speed up method for joining and cutting regions.

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EhH7CnLcoUtLuvMmCWoK_tEBxRDS9dlWr8pP86ZwdC0LCw?e=MymVJI

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot fix project file ref. 6159038267

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check document compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check documentation-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by emidio-piermarini** [comment]
@IsakNaslundBh  I've had a play with the example files and all looks good and works for the different permutations of inputs I threw at it.  I'd say its ready to be merged

**Review by emidio-piermarini — APPROVED** [review]

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
