### PR TITLE
Aligning with changes in Structure_Engine

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Engine/pull/2146/
   
### Issues addressed by this PR

https://github.com/BHoM/BHoM_Engine/issues/2135

Aligning with methods being removed from Structure_Engine.

### CODE REVIEW

**Review by peterjamesnugent — APPROVED** [review]
LGTM.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Comment by IsakNaslundBh** [comment]
The code compliance failure here is pre-existing and way outside the scope of this PR. Suggesting it to be ignored here.

**Comment by FraserGreenroyd** [comment]
> The code compliance failure here is pre-existing and way outside the scope of this PR. Suggesting it to be ignored here.

Yes @IsakNaslundBh , apologies, just borrowing this PR to test some things, was not expecting it to fail - you can ignore the report on this bit! :smile:

**Pull request merged**
