### PR TITLE
Add initial project

### LINKED ISSUE #1: Initial repo set up
Include PR template
Include issue templates
Include CI folder
Include initial TriangleNet engine

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #1 

Adds PR template
Adds Issue templates
Adds CI documentation
Adds initial engine file

Test file [Here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Compute/Triangulate.gh?csf=1&e=GlcKf4)

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@tg359 @MajaLindroth @RasmusCanfjorden this is now all set up and ready for a review :smile:

**Review by tg359 — APPROVED** [review]
Works fine for me. LGTM!

**Review by MajaLindroth — APPROVED** [review]
Test script works well for me

**Review by RasmusCanfjorden — APPROVED** [review]

**Pull request merged**
