### PR TITLE
Adding Unit Tests

### LINKED ISSUE #57: Add Unit Tests
#### Description:

As in header

### PR DESCRIPTION
**Pull request by LMarkowski**
### Issues addressed by this PR

 Closes #57 

 

 ### Test files

All scripts used for creating the unit tests are in [this folder](https://burohappold.sharepoint.com/:f:/s/BHoM/ErxuPgWlw3lEg9zCArA3fjABjtg2mB7Rtq8PiVSWaw4SJg?e=MhxRcI).

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit tests

**Review by rolyhudson — APPROVED** [review]
I have checked the test creation and all looks good.

**Review by FraserGreenroyd — APPROVED** [review]
LGTM

**Pull request merged**
