### PR TITLE
Add ToRenderMesh infrastructure and methods for basic geometry primitives

### LINKED ISSUE #26: Prototype: IMeshRepresentation interface method
#### Description:

Following https://github.com/BHoM/TriangleNet_Toolkit/issues/23 and https://github.com/BHoM/BHoM_Engine/issues/1694,

this issue is to prototype the first 2 points explained in https://github.com/BHoM/TriangleNet_Toolkit/issues/23#issuecomment-623409554.

@al-fisher

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #26

Replaces https://github.com/BHoM/BHoM_Engine/pull/1717 as we decided to move the methods in TriangleNet_Toolkit, as agreed in https://github.com/BHoM/TriangleNet_Toolkit/issues/23#issuecomment-623409554

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/Egdz58yxbjFEgFbUM8apD2YB0QD0_HuqmVa4Y35u8tVSZg?e=TFZkLc

image

image

### CODE REVIEW

**Comment by alelom** [comment]
@al-fisher I uploaded a test file that allows you to test everything, except the PlanarSurface which I will work on Tuesday.

The CI keeps complaining because it keeps collecting the old branch from Graphics_Engine, where it finds some conflicts; I deleted that, but I don't understand how, it keeps getting it.

**Review by FraserGreenroyd — DISMISSED** [review]
(Still doing a review but some initial feedback as I'm taking a break at this point given the time)

Can we avoid using `GeomRepresentation` as the folder name given `Geom` is an abbreviation. Not sure what you want to call it instead given the methods appear to be called `GeometricalRepresentation` rather than `Geometry` so will let you decide, but the abbreviation can't stay (cause it's causing confusion for me just typing this as to which it ought to be 😛 ).

**Comment by alelom** [comment]
I have added PlanarSurface. @al-fisher this is now fully ready to test and review.

The test script provides all you need to check all the features.

From a code perspective, happy to guide you through. 
Same for @FraserGreenroyd – conscious there are choices that could be deemed "strange", but they have to be read in the wider perspective that will involve future changes in both this and other repos.

**Review by al-fisher — DISMISSED** [review]
Review of current fuctionality - this is looking very good.
There are naturally some missing features - some coming from geometry engine requirements/fixes and some yet to be implemented. But I think best to raise as separate discrete improvement issues as working overall very well and already powerful.

One specific comment which I would raise @alelom for us to consider improving in a new issue is further calibration of the `Element1DRefinement` parameter. 
A common use case will be to have a UB with fillets (which I want to have a single facet say) mixed with a CHS (which I will want to facet much more to capture curvature) 
Currently arcs in the section shape are given same faceting irrespective of relative scale to overall section profile. Hope makes sense?
One to consider as improvement in future PR.

Another one to raise issue for now is moving `BH.Engine.Representation.GeometricalRepresentation` methods into a specific GeometricalRepresentation project as discussed.
As agreed we should do this next sprint as part of renaming TriangleNet_Toolkit/Engine to Mesh_Toolkit/Engine
@FraserGreenroyd @rwemay FYI

Final comment on code - we have a number of subfolders which are not reflected into a corresponding namespace. Can see the logical reasoning for this - but worth a discussion specifically on this as part of organisation of code and refactoring to separate Representation and Mesh Engines. This decision will be impacted by the Reflection and Dependancy architecture we map out to ensure this is scaleable. Again as discussed - thinking mirroring approach taken in Spatial Engine to minimise dependencies. 

@alelom - I am happy to approve if you can perhaps capture a couple of simple issues to reference the imediate next plans for refactoring and improvement?

Great stuff 👍

**Comment by al-fisher** [comment]
In addition to above comments obviously need to dig into issues with CI there. Will take a look

**Comment by FraserGreenroyd** [comment]
CI is failing on AppVeyor because:

 - BHoM is using a branch that is behind master, and does not include changes to Diffing_oM
 - BHoM_Engine is using master branch, which does include changes to Diffing_oM

The result is that BHoM_Engine does not fully build, which then travels down to this toolkit failing to build. This is resolved by the Azure CI because it does a merge into master of all PRs.

**Comment by al-fisher** [comment]
Ah, annoying - is picking up old deleted branch

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
So the compliance report has highlighted that the compute method names do not match the file name compliance check (see [here](https://github.com/BHoM/documentation/wiki/MethodNameContainsFileName)).

As discussed, we can avoid solving that this PR, but can the CSProj issue be resolved in this PR? Thanks :smile:

**Review by FraserGreenroyd — APPROVED** [review]
Approving on compliance and based on review by @al-fisher as latest commit is compliance only so happy to merge when checks are complete :smile:

**Comment by alelom** [comment]
> One specific comment which I would raise @alelom for us to consider improving in a new issue is further calibration of the `Element1DRefinement` parameter.
> A common use case will be to have a UB with fillets (which I want to have a single facet say) mixed with a CHS (which I will want to facet much more to capture curvature)
> Currently arcs in the section shape are given same faceting irrespective of relative scale to overall section profile. Hope makes sense?

@al-fisher regarding this, actually this is (should be) already implemented as a feature: I'm considering the overall scale of the element, in terms of e.g. the angle of the Arc segment, the radius of the circle, etc. 
I tested this with few sections, as well as with few polylines/polycurves, but it might well be that the the equation needs more refinement to be more effective.
Raised [separate issue](https://github.com/BHoM/TriangleNet_Toolkit/issues/31) to have a look. Do you happen to remember the pair of sections where this wasn't satisfactory so I can test?

**Comment by al-fisher** [comment]
> Raised separate issue to have a look. Do you happen to remember the pair of sections where this wasn't satisfactory so I can test?

I will try and recreate and post in the raised issue! Thanks @alelom

**Pull request merged**
