### PR TITLE
Protection and fixes for trim with boundary and openings

### LINKED ISSUE #99: An error occurred on a unit test
<samp>The following errors have been reported on unit tests in this repository.

**C:\ProgramData\BHoMGitHub\TriangleNet_Toolkit\.ci\Datasets\Compute\VoronoiRegions.json**
x.Message

**C:\ProgramData\BHoMGitHub\TriangleNet_Toolkit\.ci\Datasets\Compute\VoronoiRegions.json**
x.Message</samp>

### LINKED ISSUE #100: Add protection against no curves returned from BooleanDifference
#### Description:

Currently there is no protection against a case where no curves are returned from boolean difference which can lead to a crash in the TrimWithBoundaryAndOpenings method.

Also, the method should always be calling the Create method for planar surface to ensure that the planar surfaces are created with BoundaryCurves in possible. With current implementation this is only done for cases where the curve is intersecting an opening leading to a difference in behaviour.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #100
Closes #99

- Add protection against empty lists returned from BooleanDifference
- Make it so that PlanarSurfaces returned _always_ has external boundaries of type BoundaryCurve (alignment across both cases when trimmed with boundary and not)
- Update UTs

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EkRElFZ1zRRPlDy90IR_DQEBv7Nr_12yZ6dN9PFOWTWnLw?e=7ZPHt5

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check unit-tests

**Review by FraserGreenroyd — APPROVED** [review]
Code changes make sense and unit test is happy.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
