### PR TITLE
Fix nulls for representation namespace

### LINKED ISSUE #73: Null handling of representation part of the engine
Per title for these methods:

 - [x] BH.Engine.Representation.Compute.GeometricalRepresentation(Node node, RepresentationOptions reprOptions, Boolean isSubObject)
 - [x] BH.Engine.Representation.Compute.GeometricalRepresentation(Panel panel, RepresentationOptions reprOptions)
 - [x] BH.Engine.Representation.Compute.GeometricalRepresentation(Panel panel, RepresentationOptions reprOptions)
 - [x] BH.Engine.Representation.Compute.GeometricalRepresentation(Bar bar, RepresentationOptions reprOptions)
 - [x] BH.Engine.Representation.Compute.RenderMesh(PlanarSurface planarSurface, RenderMeshOptions renderMeshOptions)
 - [x] BH.Engine.Representation.Compute.RenderMesh(Pipe pipe, RenderMeshOptions renderMeshOptions)
 - [x] BH.Engine.Representation.Compute.RenderMesh(BoundingBox bbox, RenderMeshOptions renderMeshOptions)
 - [x] BH.Engine.Representation.Compute.RenderMesh(Cone cone, RenderMeshOptions renderMeshOptions)
 - [x] BH.Engine.Representation.Compute.RenderMesh(Cuboid cuboid, RenderMeshOptions renderMeshOptions)
 - [x] BH.Engine.Representation.Compute.RenderMesh(Extrusion extrusion, RenderMeshOptions renderMeshOptions)
 - [x] BH.Engine.Representation.Compute.RenderMesh(Sphere sphere, RenderMeshOptions renderMeshOptions)
 - [x] BH.Engine.Representation.Compute.Rationalise(PolyCurve curve, RenderMeshOptions renderMeshOptions, Int32 minSubdivisions)
 - [x] BH.Engine.Representation.Compute.RenderMesh(CompositeGeometry compositeGeometry, RenderMeshOptions renderMeshOptions)

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #73

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by rolyhudson — DISMISSED** [review]
I think we also need null checks on Rationalise Arc, Circle, ICurve too 😃

**Comment by FraserGreenroyd** [comment]
> I think we also need null checks on Rationalise Arc, Circle, ICurve too 😃

We do not - they don't fail the current null-handling checks. This PR only resolves existing null-handling checks and as per the null-handling check result, this PR reduces errors without introducing new ones :smile:

We might need to later, but I want to continue reducing the number to help the output for now so doing it in batches as seen on the engines if that's ok? :smile:

**Comment by alelom** [comment]
I will review this. We need to be a bit careful in this one with null checks.

**Review by alelom — APPROVED** [review]
This looks good and it works. 

Some future work may be needed to "catch" the null errors when methods like `RenderMesh` are used from other engine methods (the old discussion on "exception catching"). In some cases, other Engine methods might want to dynamically dispatch to `RenderMesh` methods with an input that is potentially null, treating it as an acceptable case; this other engine method may in fact want to have its own fall-back mechanism in case the result from the dynamic dispatch is returned null. In such cases, the exposure of the "input is null" error is undesiderable, as the external method will have its own workings to cope with it. In other words, ideally we should have a way to "capture" errors thrown by methods when they are used from other engine methods, in the rare cases where that is acceptable.

image

**Pull request merged**
