### PR TITLE
TriangleNet_Engine: `IRendermesh()` first checks if any RenderMesh is in CustomData; add null checks

### LINKED ISSUE #38: Add null check for obj input in IRenderMesh() and IGeometricalRepresentation()
#### Description:

To avoid weird errors downhill.

### LINKED ISSUE #39: IRenderMesh() to check if a custom RenderMesh is found in CustomData before attempting to compute a representation
#### Description:

This check and "error avoidance" is currently implemented in single Toolkits (3DRepo, Speckle). 
The logic should be centralised in the IRenderMesh() method.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Close #38 
Closes #39

A few quality of life improvements for the RenderMesh/Representation workflows:
- `IRendermesh()` first checks if any RenderMesh is in CustomData; if found, avoid attempting to compute a GeometricalRepresentation/RenderMesh. This avoids having to done this check in every Toolkit that uses `IRendermesh()`.
- Added null checks in `IRendermesh()` and `IGeometricalRepresentation()` on the input object. This avoids error in UI for null objects.
- Added `Modify.SetRenderMesh()`. This attaches an input `RenderMesh` to a BHoMObject's CustomData. If the input is not a `RenderMesh`, it tries computing the RenderMesh for it.

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EhlSw8CPOXJEmMZnBdLhYRoBj_nKgzazrvE4iBa0s8Unmw?e=Ry1nDh

### Changelog

- `IRendermesh()` first checks if any RenderMesh is in CustomData; if found, avoid attempting to compute a GeometricalRepresentation/RenderMesh. This avoids having to done this check in every Toolkit that uses `IRendermesh()`.
- Added null checks in `IRendermesh()` and `IGeometricalRepresentation()` on the input object. This avoids error in UI for null objects.
- Added `Modify.SetRenderMesh()`. This attaches an input `RenderMesh` to a BHoMObject's CustomData. If the input is not a `RenderMesh`, it tries computing the RenderMesh for it.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
Have added a `do-not-merge` label as this is a feature and we're now in final sprint. Label can be removed at end of the sprint.

**Comment by FraserGreenroyd** [comment]
I have removed the `do-not-merge` label from this as it's now out of feature sprint. @alelom can you confirm status of the PR in terms of being ready for review?

**Comment by alelom** [comment]
> I have removed the `do-not-merge` label from this as it's now out of feature sprint. @alelom can you confirm status of the PR in terms of being ready for review?

Confirmed.

**Comment by alelom** [comment]
@al-fisher same said for https://github.com/BHoM/BHoM_Engine/pull/1900#issuecomment-667884260

**Review by al-fisher — APPROVED** [review]
Approved - as per @alelom comment. This has been tested on a number of prototype diffing workflows
Good to merge now

**Pull request merged**
